### ISSUE TITLE
Design resource element

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#13]
[Design the look of the resource item.](https://github.com/ufosc/club-website/blob/dev/docs/references/mobile-other-pages.jpg) Mock up with HTML and CSS what it would look like with some example content (don't worry about actually getting the information, that's issue #11). It should have a spot for the technology name, description, and links for it. It should resize for desktop and mobile devices.

**Comment by paologarcia002** [comment]
Question, is this just for mobile or mobile and desktop?

**Comment by mirdaki** [comment]
It should be for both desktop and mobile devices. There was just a mobile reference, because I ran out of paper...

**Comment by paologarcia002** [comment]
![image](https://user-images.githubusercontent.com/35015371/35418039-0fb0b76c-01fe-11e8-866f-b547c6042eb9.png)

Ok this is what i have for the resources page and the respective html:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Resources</title>
    <link rel="stylesheet" href="resources.css">
    <link rel="stylesheet" href="main.css">
</head>

<body>

    
    <section id="upper bar">
        <a href="home.html"><img src="logo.png" height="25.5em" width="50em"></a>
        
        <button class="drowpdown">&#9776;</button>
    </section>

    
    <section>
        <h1>Resources</h1>
        <p>
            Here are some resources for you to use, whether it be programming 
            language documentation or some other stuff, all of that
            is here.
        </p>
    </section>

    
    <article class="link_groupings">
        <section class="link_group">
            <h3>Technology 1</h3>
            <p>
                some description
            </p>
            
            <a href="link1.com">Link 1</a>
            <a href="link2.com">Link 3</a>
            <a href="link3.com">Link 2</a>
        </section>

        <section class="link_group">
            <h3>Technology 2</h3>
            <p>
                some description
            </p>
            <a href="link1.com">Link 1</a>
            <a href="link2.com">Link 3</a>
            <a href="link3.com">Link 2</a>
        </section>

        <section class="link_group">
            <h3>Technology 3</h3>
            <p>
                some description
            </p>
            <a href="link1.com">Link 1</a>
            <a href="link2.com">Link 3</a>
            <a href="link3.com">Link 2</a>
        </section>
    </article>

    
    <section>
        <h3>Footer thing</h3>
        <a href="link1.com">Link 1</a>
        <a href="link2.com">Link 3</a>
        <a href="link3.com">Link 2</a>
    </section>

</body>

</html>

**Comment by mirdaki** [comment]
Nice progress!

**Comment by paologarcia002** [comment]
Is there anything else i should try to do before i try to push other than the borders going too far when full screen?

![image](https://user-images.githubusercontent.com/35015371/35836505-8f0e2de2-0aae-11e8-9250-8e28b78643fc.png)

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Resources</title>
    <link rel="stylesheet" href="resources.css">
    <link rel="stylesheet" href="main.css">
</head>

<body>
    
    <section class="resources">
        <h1>Resources</h1>
        <p>
            Here are some resources for you to use, whether it be programming 
            language documentation or some other stuff, all of that
            is here.
        </p>
    </section>

    
    <article class="link_groupings">
        <section id="link_group1">
            <h3>Technology 1</h3>
            <p>
                Some description.
            </p>
            
            <a href="link1.com">Link 1</a>
            <a href="link2.com">Link 3</a>
            <a href="link3.com">Link 2</a>
        </section>

        <section id="link_group2">
            <h3>Technology 2</h3>
            <p>
                Some description.
            </p>
            <a href="link1.com">Link 1</a>
            <a href="link2.com">Link 3</a>
            <a href="link3.com">Link 2</a>
        </section>

        <section id="link_group3">
            <h3>Technology 3</h3>
            <p>
                Some description.
            </p>
            <a href="link1.com">Link 1</a>
            <a href="link2.com">Link 3</a>
            <a href="link3.com">Link 2</a>
        </section>
    </article>

</body>

</html>

body {
    font-family: Arial, Helvetica, sans-serif;
    margin: 1em;
    border: 1em;
    padding: 1em;
    display: flex;
    flex-wrap: wrap;
    flex-direction: column;
    text-align: center;
    border-radius: 25px;
}

article {

}

section {

}

h1, h3 {
   padding: .25em;
   margin: .1em;
}

p {
    font-size: 12pt;
}

a {
    font-size: 10pt;
}

a:hover{
    color:orangered;
}

.resources {
    margin: .01em;
    border: .01em;
    padding: .01em;
}


#link_group1, #link_group2, #link_group3 {
    margin-top: .25em;
    border: .15em solid black;
    padding: .75em;
    flex: 2;
}

**Comment by mirdaki** [comment]
I would suggest you explore some different theme-ing options (different [fonts](https://fonts.google.com/),  positioning, etc). Also it might be easier to judge themes if you have more placeholder text in the description. Once you find some combo you like, then submit it!

**Comment by paologarcia002** [comment]
Ok will do!

**Comment by mirdaki** [comment]
Finished with #19
