### ISSUE TITLE
 Design project element

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#14]
[Design the look of an individual project item.](https://github.com/ufosc/club-website/blob/dev/docs/references/mobile-other-pages.jpg) Mock up with HTML and CSS what it would look like with some example content (don't worry about actually getting the information, that's issue #10). It should have a spot for the name of the project, a description, the project lead, links to the GitHub and other project contributors, and an optional image.  It should resize for desktop and mobile devices.

**Comment by jjmorales** [comment]
![image](https://user-images.githubusercontent.com/35714262/35457659-b387bd50-02a7-11e8-87f0-b00806ef428e.png)

This is the template I built, feedback please

@mirdaki

**Comment by jjmorales** [comment]
So there's a spot for the title, project lead, project description, image, github link, and contributors. I filled it all in with random stuff about the migos just so you can see it in action.

**Comment by mirdaki** [comment]
Nice job! It has everything we need and is well laid out. Could you look into different font choices (each part can be a different font too) to make it feel a little more polished? This is a [good resource](https://fonts.google.com/) to start

**Comment by jjmorales** [comment]
Thanks! Okay will do

**Comment by jjmorales** [comment]
![image](https://user-images.githubusercontent.com/35714262/35458998-900aa19e-02ac-11e8-987b-ae22aa9be965.png)

I changed the fonts and moved the git and contribution section to the middle (I could move it back, just a change so you could decide whether you prefer it on the side or the middle)... are these fonts okay or should I keep looking? What do you think of the placement for the git and contribution, middle or left hand side?

**Comment by mirdaki** [comment]
On the fonts: I think the title font is a bit to block and rough (not sure if that's the right word lol) for a project (makes sense for an album though). Try a few different combinations and post what you like. 

On the GitHub link and contributions I think center is fine. One thing we might have to deal with is if the project dosen't have a picture. If that happens the element should adjust appropriately.

**Comment by jjmorales** [comment]
![screen shot 2018-01-26 at 4 54 40 pm](https://user-images.githubusercontent.com/35714262/35462666-e9f9e94a-02ba-11e8-941c-4ecc020dc3bb.png)
![screen shot 2018-01-26 at 5 03 28 pm](https://user-images.githubusercontent.com/35714262/35462667-ea0bfc70-02ba-11e8-9b8a-8d9899a32557.png)
![screen shot 2018-01-26 at 5 06 29 pm](https://user-images.githubusercontent.com/35714262/35462750-4b1b1a3c-02bb-11e8-9d40-376cb8211dc1.png)


This is a different font for the title,  it's a more simple, sleek and thin look. 

Also, in the case that there is no image, you simply have to put the description in a different div leaving the column divs empty, I labeled each portion of code with short comments saying what goes where, I included a screenshot of a chunk of the code so you sort of get the idea of what I was going for. I'm less explicit with what classes in css go to what but I feel those are sort of self explanatory and could be figured out by looking at what code implements what style class.

**Comment by mirdaki** [comment]
I do like title font better. Good job with the comments too. It does look like the GitHub link and contributors isn't quite centered without the picture though. Also can I ask why you're using divs around the h1 and h4?

**Comment by jjmorales** [comment]
Ah nice catch, I had them wrapped in divs because I was experimenting with some other organizational styles but then decided against it. I removed them for cleaner code. I'll work on the alignment of the GitHub link and contributors. If we decide that we want those attributes on the left instead of the middle then there's no issue and they remain in the same spot regardless on if there's an image or not. If we want those attributes centered it becomes a little more complicated and I'd need to reformat some stuff a little bit. Do you want me to keep those centered or put them back on the left?

**Comment by mirdaki** [comment]
Lets try centering for now

**Comment by jjmorales** [comment]
![screen shot 2018-01-26 at 7 11 52 pm](https://user-images.githubusercontent.com/35714262/35465818-d86bdb2c-02cc-11e8-9638-79ba52962ef2.png)
![screen shot 2018-01-26 at 7 11 22 pm](https://user-images.githubusercontent.com/35714262/35465819-d87e9a82-02cc-11e8-8003-84026ac2794f.png)

I think I got it.

**Comment by mirdaki** [comment]
Nice! Now could you make a list of these to represent different projects to simulate a full page. After that you can merge your code with the dev branch. You could name your files something like project-page.html and project-page.css so they don't get confused for another part.

**Comment by jjmorales** [comment]
I filled in the code with random information and bs just so you could see how it looks as a full page. Do you want me to submit it with the example content so they have an idea of what it looks like and where things go?

**Comment by mirdaki** [comment]
Yep! Have a mix of them with and without images

**Comment by jjmorales** [comment]
Yes sirrrr I did that. How do I split the files up making one css and one html?

**Comment by jjmorales** [comment]
Nevermind I looked it up! I'll merge now

**Comment by mirdaki** [comment]
Nice job!! I'll close this issue now, want another one?

**Comment by jjmorales** [comment]
Yeah sure! Did you take a look at the files I submitted?

**Comment by mirdaki** [comment]
I did. The code looks pretty good (and you have a knack for filling out the contributor section lol)! I've assigned you to issue #9!
