### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#17]
We need the home page layout as seen [here](https://github.com/ufosc/club-website/blob/dev/docs/references/desktop-home.jpg) and [here](https://github.com/ufosc/club-website/blob/dev/docs/references/mobile-home.jpg). It should have a section for: the slideshow, promote, support, create, upcoming events, and how to get involved. **Note:** Don't worry about implementing the header (#6), footer (#7), slideshow (#8), or upcoming events (#9), as those are different tasks. Just create an empty element of those sizes as a place holder. The promote, support, and create should each have a title, image, and text area to describe the club (similar to this [example](https://www.glucosio.org/)). The get involved section should be a title and description. It should all be resizable for mobile and desktop devices.

**Comment by mirdaki** [comment]
Look into using [CSS grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) and [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)

**Comment by lucasgrinspan** [comment]
![osc](https://user-images.githubusercontent.com/32201603/35519505-766b668c-04e2-11e8-97b4-7fe96b2605e9.PNG)
This is what I have so far using CSS grid. Am I on the right track?

**Comment by mirdaki** [comment]
Yes! It looks good so far! Don't forget to add a section for upcoming events. Once you feel like you have the overall design working for both desktop and mobile, try fleshing out the design of the promote, support, and create sections.

**Comment by mirdaki** [comment]
Finished with commit 3701318
