### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#27]
A favicon is the little icon you see in a tab. Ours should be the club logo (it might need a background). It'd be great if we could just use the "small-logo.png" already in the assets folder. Remember to add the favicon to all the pages on the website.

**Comment by marcusmills0926** [comment]
Hey, I'm interested in working on this

**Comment by mirdaki** [comment]
Awesome, let me know if you have any questions!

**Comment by mirdaki** [comment]
Completed with #38
