### ISSUE TITLE
Make the website responsive 

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#3]
## Description

Implement responsive design (have the website resize and arrange itself on different screen sizes). The experience on: 
- [x] small phones
- [x] phones 
- [x] tablets
- [x] laptops
- [x] desktops 

should be pleasant and present all the required information (from issue #2)

### Examples

One way to do it might be using [CSS grids with media queries](https://gridbyexample.com/examples/example13/). If you have another idea, please comment about it below!

**Comment by fpineirolopez** [comment]
Why not use Bootstrap? It helps with making websites responsive and its really easy to use. 

If you are not familiar here is the link to their main page to learn more about it: http://getbootstrap.com/ 

I have been working in another website and I have used bootstrap to code it and make it responsive, so I would be happy to do this part if we decide to use it.

**Comment by mirdaki** [comment]
I know the original idea was this was supposed to be more of a learning experience for people new to web design. So we had talked about not using a framework. I'll talk to @CSugarPrince (the project lead) to see if he wants to change that.

**Comment by fpineirolopez** [comment]
Sounds good!

**Comment by mirdaki** [comment]
Sorry for the delay, but the plan is still not to use bootstrap or another framework. I will say making a site responsive using a combination of CSS grid and media queries is fairly easy for a simple site (like ours). This is a pretty good [example](https://gridbyexample.com/examples/example13/) if you're curious.

**Comment by fpineirolopez** [comment]
Ok, thank you! I can start learning this stuff, but i will be pretty busy until next week. After that I can dedicate some time and work on this

**Comment by mirdaki** [comment]
Awesome! Feel free to ask any questions here or at one of our [casual coding sessions](https://www.facebook.com/groups/ufosc/events/).

**Comment by mirdaki** [comment]
We are happy with the results right now for the V1
