### ISSUE TITLE
Fix nav-bar scaling in "tablet" sized screens

### ISSUE THREAD

**Issue by dylanalvarez1** [ufosc/club-website#35]
Fix visual issue where the nav-bar is too obstrusive in a certain range of screen dimensions such as medium sized screens (600 x 900 for example).

**To Reproduce**
Go to browser dev tools, and change the screen size to 600 x 900.

**Expected behavior**
Rearrange the nav-bar so it displays the different options in a less obtrusive way.

**Screenshots**
![image](https://user-images.githubusercontent.com/25395901/45779356-c8e58980-bc28-11e8-8713-f08a47075ee7.png)

**Comment by mirdaki** [comment]
The eventual goal is to have the menu hover over the content (instead of push it down), kind of like this 
![image](https://user-images.githubusercontent.com/8786151/47664289-1ed91580-db75-11e8-8863-2f897823460c.png)

**Comment by ZPPD** [comment]
Can I get this issue?

**Comment by mirdaki** [comment]
@ZPPD Sure! Let us know if you have any questions or suggestions

**Comment by ZPPD** [comment]
Thanks @mirdaki . I can't assign myself, but I will work on it tomorrow

**Comment by ZPPD** [comment]
@mirdaki 
I am testing it on Chrome and Firefox. There is an empty div with a class of topnav-placeholder.
On the left is Firefox, where I have removed the empty div. On the right is Chrome with the empty div, which has a height of 60px. 
Do you want me to keep the div? And is this what you are looking for for the design?

![club-website-menu](https://user-images.githubusercontent.com/38818964/52727784-f5a58f00-2f83-11e9-9b35-2dfecef448a1.png)

**Comment by mirdaki** [comment]
Sorry for not getting back sooner. I feel like the left without the div looks the best! Thank you for your help

**Comment by mirdaki** [comment]
Fixed with #63
