### ISSUE TITLE
Remove ".html" from URL

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#53]
The ".html" looks a little unprofessional, as does having the home page go to "index.html". I'd like the current navigation to work without the ".html" and ".html". 

The ".html" part probably needs to be changed in the [nginx config](https://github.com/ufosc/club-stack/blob/master/nginx/ufopensource.club.conf). Though there might be some other option. 

The "index.html" I think can be fixed with the homepage links on the other pages.

## Resources

- [index.html example](https://stackoverflow.com/questions/22481028/removing-the-index-html-from-url)
- [nginx example](https://serverfault.com/questions/586263/dynamic-url-in-nginx-configuration)

**Comment by vvtrip** [comment]
I have a PR on nginx config file changes.

**Comment by mirdaki** [comment]
[This](https://stackoverflow.com/questions/38228393/nginx-remove-remove-html-extension) configuration seems to be working
