### ISSUE TITLE
Redirect old website

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#55]
The [old website](https://github.com/ufosc/ufosc.github.io) should redirect to the new one. Because it was hosted on GitHub, we'll need to use a client side option.

Once that works, make sure to minimize each page so they quickly redirect.

## Resource

- [Options](https://css-tricks.com/redirect-web-page/)

**Comment by clink73** [comment]
This has to be added to the old website instead of this website, so I have made the change here: https://github.com/ufosc/ufosc.github.io/pull/8

I wasn't sure what you meant by "make sure to minimize each page so they quickly redirect". Can you explain?

**Comment by mirdaki** [comment]
Awesome! Thanks for the assistance @clink73.

I meant that we should basically remove the rest of the content from the webpage so it doesn't waste time trying to load the old site before redirecting.

Also be sure to update the redirect to go to `http://ufopensource.club/`!

**Comment by mirdaki** [comment]
This has been done with commit 7e79200 on the [old repo](https://github.com/ufosc/ufosc.github.io).
