### ISSUE TITLE
Update the nav bar to use Flexbox

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#58]
Currently the CSS for the navigation bar (both in desktop and mobile modes) does not use Flexbox for positioning items. This means the code is messy then it needs to be. It would also be nice to use more up-to-date options as well. 

Look through the Flexbox walk though on [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) and update both the desktop and mobile versions of the navigation bar to use Flexbox.

**Comment by okawa-h** [comment]
Can I work on this issue?

**Comment by mirdaki** [comment]
Sure! Feel free to ask questions here or in our [Discord](https://discord.gg/Gsxej6u)

**Comment by Priyanka-ashok** [comment]
I hope the issue isn't resolved yet.. So can i work too on the issue?

**Comment by mirdaki** [comment]
Hey @Priyanka-ashok! I appreciate the interest in helping out with this issue, but okawa-h is currently working on it

**Comment by mirdaki** [comment]
Closed with #59
