### ISSUE TITLE
Make site header

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#6]
The header should include the logo, links to the other pages on the website. It should also resize on smaller devices. To avoid clutter, the links should be hidden by some sort of menu button. When clicked the button should un-collapse and show the links.

**Comment by mirdaki** [comment]
The design references can be found [here](https://github.com/ufosc/club-website/tree/dev/docs/references)

**Comment by JING1201** [comment]
I've kind of finish the basic structure/design of the header, should I push to the dev-branch or post the code/screenshot here?

**Comment by mirdaki** [comment]
Post a screenshot here so we can see!

**Comment by JING1201** [comment]
![website header 1](https://user-images.githubusercontent.com/19191124/35129189-79d12594-fc88-11e7-9561-0800c3e4bb9b.PNG)
![website header 2](https://user-images.githubusercontent.com/19191124/35129191-79e3cb9a-fc88-11e7-932c-f72a2ef366bd.PNG)
![website header 3](https://user-images.githubusercontent.com/19191124/35129192-79f92c88-fc88-11e7-9cbf-c838f24ec58d.PNG)
Here are the looks!

**Comment by mirdaki** [comment]
Awesome job! Could you please push it to dev in a header.html file (or something like that)
