### ISSUE TITLE
Rename all CSS classes to use Title style names

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#66]
There was no class naming scheme at the start of this project. As a result, the current names are kind of a mess and I'm sure the CSS rules are more complicated because of it. I purpose (though I'm open to other suggestions) that we adopt the [Title](https://www.sitepoint.com/title-css-simple-approach-css-class-naming/) naming scheme, because it is simple and clean. 

We need to:
- [ ] Update all class and ID names, using the new naming scheme, in the HTML files and their corresponding CSS
- [ ] After verifying the old rules till work, reduce and simplify CSS rules using the new names. Make sure that the actual look of the page is not altered negatively 
- [ ] Add a CSS style guide (it should go into the club-resources repo, but we need to link to it from here) that includes the naming scheme and anything else that makes sense

**Comment by logandgsmith** [comment]
Addressing this in #72.
