### ISSUE TITLE
Make site footer

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#7]
It should have links to our Facebook, GitHub, and Slack, preferably with icons for each site. Needs to be responsive on both desktop and mobile devices. Design references can be found [here](https://github.com/ufosc/club-website/tree/dev/docs/references).

**Comment by mirdaki** [comment]
Maybe also include the clubs email too

**Comment by lucasgrinspan** [comment]
![footer 1](https://user-images.githubusercontent.com/32201603/36636631-43960846-1998-11e8-9e8e-49a922184ca8.png)
![footer 2](https://user-images.githubusercontent.com/32201603/36636632-43ab8414-1998-11e8-86ed-d3d2cc1197f7.png)
![footer 3](https://user-images.githubusercontent.com/32201603/36636633-43ca78e2-1998-11e8-807d-faa4e7d79b94.png)
I have 3 possible designs so far that I like. I accidentally took the screenshots on different screen sizes so ignore the random size differences. All the links and images turn white when you hover over them. Which do you prefer?

**Comment by mirdaki** [comment]
I like the last one the most. I guess I didn't explain it well enough, but the links are the icons (as in their are no separate links, just the icons)

**Comment by mirdaki** [comment]
Finished in #24
