### ISSUE TITLE
Make slideshow

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#8]
It should have an auto-scrolling slide show that is responsive on both desktop and mobile devices. There should be arrows on either side to manually scroll through. Use minimal JavaScript if it's needed. References can be found [here](https://github.com/ufosc/club-website/tree/dev/docs/references).

**Comment by dylanalvarez1** [comment]
@mirdaki for organization/style, would you rather the javascript be a separate file or just in the script tag?

**Comment by mirdaki** [comment]
Could you add it as a separate "index.js' file under a "scripts" folder?

**Comment by dylanalvarez1** [comment]
I can do that, also where can i find the images to display in the slideshow, I searched the google drive, the clubs assets in the github, as well as this repo's assets.

**Comment by mirdaki** [comment]
Closed with #33
