### ISSUE TITLE
Make upcoming event element

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-website#9]
It's similar to issue #5, but instead should only show and link to the next few events. Should be responsive on both desktop and mobile devices. Design references can be found [here](https://github.com/ufosc/club-website/tree/dev/docs/references).

**Comment by mirdaki** [comment]
I want to clarify, this is just a template for showing the next few upcoming events on the home page. Not actually pulling in that data.

**Comment by jjmorales** [comment]
How many events do you want visible, like when you say recent do you mean like 3 upcoming events? 

Also, do you simply want to be able to link something? Or do you want a spot for a title, short description, then a link?

**Comment by mirdaki** [comment]
Good questions lol. I think three events is good. It should have a title, short description, and a link to the corresponding Facebook event.

**Comment by mirdaki** [comment]
Finished with #26
